[package]
name = "anymsg"
version = "0.1.0"
authors = ["archshift <gh@archshift.com>"]
license = "MIT"
repository = "https://github.com/archshift/anymsg"
description = "Type-routed message passing infrastructure"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "throughput"
harness = false
